### ISSUE TITLE
Windows-containers launched by selenoid do not respond in 30s

### ISSUE THREAD

**Issue by NavySeal5** [aerokube/windows-images#24]
So i have built the windows-images according to the guide (which was very helpful) and played around with them for a big and have encountered one issue.
When i try to launch these images with Selenoid, the container fails to start with the following message: 
```
selenoid_1     | 2019/11/13 11:09:26 [1] [SERVICE_STARTUP_FAILED] [wait: http://172.24.0.4:4444/ does not respond in 30s]
```
However when i launch the containers myself i can connect to them via vnc just fine and also tests against the Webdriver running inside work. So my only issue is the containers not seeming to work together with Selenoid.

I am using docker-compose to launch selenoid together with selenoid-ui, the docker-compose file:
```
version: '3'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - "/home/wdadm/selenoid/config/:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4444:4444"
    networks:
      - internal
    command: ["-container-network","selenoid_internal"]
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    ports:
      - "8080:8080"
    command: ["--selenoid-uri","http://selenoid:4444"]
    networks:
      - internal
networks:
  internal:
    driver: bridge
```

I am doing all this on Ubuntu 18.04 running in a Hyper-V on Windows 10

**Comment by vania-pooh** [comment]
@NavySeal5 is network name `selenoid_internal`?

**Comment by NavySeal5** [comment]
yes, the folder the docker-compose file is in is called selenoid, so the network docker creates is called selenoid_internal, also selenoid does work with the prebuilt containers (chrome/firefox) just not with my own built ones

**Comment by vania-pooh** [comment]
@NavySeal5 two possible reasons:
1) Your containers are starting too slowly. In that case you just need to increase `-service-startup-timeout` e.g. to `1m`.
2) There is an issue in image and for some reason it takes a lot of time to start webdriver.

**Comment by emilorol** [comment]
I have seem the windows VM take a bit longer than native chrome or firefox containers to start. I also added to the selenoid server the start with the following params, so the test don't fail due to a time out:

```
./cm selenoid start --browsers-json ~/config/browsers.json --force --args "-limit 20 -session-attempt-timeout 3m -service-startup-timeout 3m"
```

**Comment by NavySeal5** [comment]
@vania-pooh 
1. I don't think that this is actually the problem here, since when manually starting the containers they seem to be ready within a minute (able to connect to vnc and start tests)

2. I also dont think that this might be the issue, since i created the memory snapshot of the windows-vm with webdriver already running, so as soon as the vm runs, the webdriver also runs

@emilorol 
As mentioned above i dont think my main issue here is the time it takes to start those containers, but more of a proxying/networking problem
I have tried to set the timeout to up to 10 minutes, but still get the same Problem
Here is the output of my last try of launching one of each containers:
```
selenoid_1     | 2019/11/14 12:44:14 [-] [INIT] [Loading configuration files...]
selenoid_1     | 2019/11/14 12:44:14 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
selenoid_1     | 2019/11/14 12:44:14 [-] [INIT] [Video Dir: /opt/selenoid/video]
selenoid_1     | 2019/11/14 12:44:14 [-] [INIT] [Your Docker API version is 1.39]
selenoid_1     | 2019/11/14 12:44:14 [-] [INIT] [Timezone: UTC]
selenoid_1     | 2019/11/14 12:44:14 [-] [INIT] [Listening on :4444]
selenoid-ui_1  | 2019/11/14 12:44:15 [INIT] [Listening on :8080]
selenoid-ui_1  | 2019/11/14 12:44:18 Client added. 1 registered clients
selenoid-ui_1  | 2019/11/14 12:44:27 Client added. 2 registered clients
selenoid_1     | 2019/11/14 12:44:29 [-] [NEW_REQUEST] [unknown] [192.168.38.49]
selenoid_1     | 2019/11/14 12:44:29 [-] [NEW_REQUEST_ACCEPTED] [unknown] [192.168.38.49]
selenoid_1     | 2019/11/14 12:44:29 [4] [LOCATING_SERVICE] [edge] [18.0]
selenoid_1     | 2019/11/14 12:44:29 [4] [USING_DOCKER] [edge] [18.0]
selenoid_1     | 2019/11/14 12:44:29 [4] [CREATING_CONTAINER] [docker.workflow.at/selenoid-edge:18]
selenoid_1     | 2019/11/14 12:44:30 [4] [STARTING_CONTAINER] [docker.workflow.at/selenoid-edge:18] [bff728c53f41e3433d9e1d631abf6ccb903c064b832853fdf07ef7fdb90fd0f4]
selenoid_1     | 2019/11/14 12:44:30 [4] [CONTAINER_STARTED] [docker.workflow.at/selenoid-edge:18] [bff728c53f41e3433d9e1d631abf6ccb903c064b832853fdf07ef7fdb90fd0f4] [0.79s]
selenoid_1     | 2019/11/14 12:44:33 [-] [NEW_REQUEST] [unknown] [192.168.38.49]
selenoid_1     | 2019/11/14 12:44:33 [-] [NEW_REQUEST_ACCEPTED] [unknown] [192.168.38.49]
selenoid_1     | 2019/11/14 12:44:33 [6] [LOCATING_SERVICE] [ie] [11.0]
selenoid_1     | 2019/11/14 12:44:33 [6] [USING_DOCKER] [ie] [11.0]
selenoid_1     | 2019/11/14 12:44:33 [6] [CREATING_CONTAINER] [docker.workflow.at/selenoid-ie:11]
selenoid_1     | 2019/11/14 12:44:34 [6] [STARTING_CONTAINER] [docker.workflow.at/selenoid-ie:11] [c399702d8b2eb7d3fad902ef50858fcd1af2fd823097b56c256335fc4b401555]
selenoid_1     | 2019/11/14 12:44:35 [6] [CONTAINER_STARTED] [docker.workflow.at/selenoid-ie:11] [c399702d8b2eb7d3fad902ef50858fcd1af2fd823097b56c256335fc4b401555] [0.99s]
selenoid_1     | 2019/11/14 12:46:13 [6] [SERVICE_STARTED] [docker.workflow.at/selenoid-ie:11] [c399702d8b2eb7d3fad902ef50858fcd1af2fd823097b56c256335fc4b401555] [97.83s]
selenoid_1     | 2019/11/14 12:46:13 [6] [PROXY_TO] [c399702d8b2eb7d3fad902ef50858fcd1af2fd823097b56c256335fc4b401555] [http://172.24.0.5:4444/wd/hub]
selenoid_1     | 2019/11/14 12:46:13 [6] [SESSION_ATTEMPTED] [http://172.24.0.5:4444/wd/hub] [1]
selenoid_1     | 2019/11/14 12:46:13 [6] [SESSION_FAILED] [http://172.24.0.5:4444/wd/hub] [405 Method Not Allowed]
selenoid_1     | 2019/11/14 12:46:13 [6] [REMOVING_CONTAINER] [c399702d8b2eb7d3fad902ef50858fcd1af2fd823097b56c256335fc4b401555]
selenoid_1     | 2019/11/14 12:46:19 [6] [CONTAINER_REMOVED] [c399702d8b2eb7d3fad902ef50858fcd1af2fd823097b56c256335fc4b401555]
selenoid_1     | 2019/11/14 12:54:30 [4] [REMOVING_CONTAINER] [bff728c53f41e3433d9e1d631abf6ccb903c064b832853fdf07ef7fdb90fd0f4]
selenoid_1     | 2019/11/14 12:54:32 [4] [CONTAINER_REMOVED] [bff728c53f41e3433d9e1d631abf6ccb903c064b832853fdf07ef7fdb90fd0f4]
selenoid_1     | 2019/11/14 12:54:32 [4] [SERVICE_STARTUP_FAILED] [wait: http://172.24.0.4:4444/wd/hub does not respond in 10m0s]
```
Also here is my browsers.json i am using right now, i am not sure wether or not i have to put the full `"/wd/hub"` to my windows images, but i have tried both ways and always had the same result
```
{
    "chrome":{
        "default":"78.0",
        "versions":{
            "78.0":{
                "image":"selenoid/vnc:chrome_78.0",
                "port":"4444",
                "path":"/"
            }
        }
    },
    "firefox":{
        "default":"70.0",
        "versions":{
            "70.0":{
                "image":"selenoid/vnc:firefox_70.0",
                "port":"4444",
                "path":"/wd/hub"
            }
        }
    },
    "ie":{
        "default":"11.0",
        "versions":{
            "11.0":{
                "image":"docker.workflow.at/selenoid-ie:11",
                "port":"4444",
                "path":"/wd/hub"
            }
        }
    },
    "edge":{
        "default":"18.0",
        "versions":{
            "18.0":{
                "image":"docker.workflow.at/selenoid-edge:18",
                "port":"4444",
                "path":"/wd/hub"
           }
        }
    }
}
```

**Comment by emilorol** [comment]
Change your IE and Edge configurations in your `browsers.js` as follow:

```
    "internet explorer": {
        "default": "11.0",
        "versions": {
            "11.0": {
                "image": "docker.workflow.at/selenoid-ie:11",
                "port": "4444",
                "path": "/",
                "privileged": true
            }
        }
    },
    "MicrosoftEdge": {
        "default": "18.0",
        "versions": {
            "18.0": {
                "image": "docker.workflow.at/selenoid-edge:18",
                "port": "4444",
                "path": "/",
                "privileged": true
            }
        }
    }
```
I think there is a chance that might solve the issue you are having. Also notice that you will not be able to `manually` start the containers from the `selenoid-ui` for IE and Edge until the following PR aerokube/selenoid-ui#253 or something like it get merged into `selenoid-ui` .

After you change your `browsers.js` and restart `selenoid` to take the changes you can use `curl`, `postman` or `ARC` to test your setup:

![Edge](https://user-images.githubusercontent.com/9518604/68873183-41c95f80-06cd-11ea-8d22-521ff9013be6.png)

**Comment by vania-pooh** [comment]
@emilorol in Selenoid containers are always running in `privileged` mode.

**Comment by emilorol** [comment]
@vania-pooh got it. I will update my personal `browsers.js`, but it does not hurt to have it.

**Comment by toni-moreno** [comment]
Hi everybody. 
Same Issue for me over docker in debian , with docker-compose.

```yaml
version: '3'
services:
  selenoid:
    container_name: test-selenoid
    image: aerokube/selenoid:1.9.3
    networks:
      - selenoid-net
    command: 
      - -container-network=${PROJECT_NAME}_selenoid-net

    ports:
     - "4444:4444"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./browsers.json:/etc/selenoid/browsers.json:ro
     - ./video:/opt/selenoid/video

  selenoid-ui: 
    container_name: test-selenoid-ui
    image: aerokube/selenoid-ui:1.9.0
    networks:
      - selenoid-net
    command:
      - "-selenoid-uri=http://selenoid:4444"
    ports:
     - "8080:8080"

networks:
  selenoid-net:
```


Logs when force create session from selenoid-ui
```
test-selenoid  | 2019/11/14 16:11:26 [-] [INIT] [Loading configuration files...]
test-selenoid  | 2019/11/14 16:11:26 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
test-selenoid  | 2019/11/14 16:11:26 [-] [INIT] [Video Dir: /opt/selenoid/video]
test-selenoid  | 2019/11/14 16:11:26 [-] [INIT] [Your Docker API version is 1.40]
test-selenoid  | 2019/11/14 16:11:26 [-] [INIT] [Timezone: UTC]
test-selenoid  | 2019/11/14 16:11:26 [-] [INIT] [Listening on :4444]
test-selenoid  | 2019/11/14 16:11:51 [-] [NEW_REQUEST] [unknown] [172.24.0.1]
test-selenoid  | 2019/11/14 16:11:51 [-] [NEW_REQUEST_ACCEPTED] [unknown] [172.24.0.1]
test-selenoid  | 2019/11/14 16:11:51 [5] [LOCATING_SERVICE] [MicrosoftEdge] [18]
test-selenoid  | 2019/11/14 16:11:51 [5] [USING_DOCKER] [MicrosoftEdge] [18]
test-selenoid  | 2019/11/14 16:11:51 [5] [CREATING_CONTAINER] [windows/edge:18]
test-selenoid  | 2019/11/14 16:11:52 [5] [STARTING_CONTAINER] [windows/edge:18] [e9f2b02357f8a14949c86056505819e8b2f8052ab7386d753ff11440be3bf26e]
test-selenoid  | 2019/11/14 16:11:52 [5] [CONTAINER_STARTED] [windows/edge:18] [e9f2b02357f8a14949c86056505819e8b2f8052ab7386d753ff11440be3bf26e] [0.64s]
test-selenoid  | 2019/11/14 16:12:22 [5] [REMOVING_CONTAINER] [e9f2b02357f8a14949c86056505819e8b2f8052ab7386d753ff11440be3bf26e]
test-selenoid  | 2019/11/14 16:12:23 [5] [CONTAINER_REMOVED] [e9f2b02357f8a14949c86056505819e8b2f8052ab7386d753ff11440be3bf26e]
test-selenoid  | 2019/11/14 16:12:23 [5] [SERVICE_STARTUP_FAILED] [wait: http://172.17.0.2:4444/ does not respond in 30s]
```
The same with any available browser
