### ISSUE TITLE
Starting Windows container from Selenoid

### ISSUE THREAD

**Issue by telesma** [aerokube/windows-images#8]
I have successfully build a container with running windows inside from your guide. Thanks a lot for the detailed instructions! 

It works also as described when running the container like this:
`$ docker run -it --rm --privileged -p 4444:4444 -p 5900:5900 windows/ie:11`
I am able to run tests successfully against the container.

Now I want to start the container from Selenoid on the host system. Selenoid is able to start the image successfully but the service inside is not starting. For me it looks like `--privileged` flag is missing in browser.json configuration. Is there a way to achieve this?

docker-compose:
```
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    network_mode: bridge
    volumes:
      - "$PWD/selenoid/config:/etc/selenoid/"
      - "$PWD/selenoid/opt:/opt/selenoid/video"
      - "$PWD/selenoid/opt:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR="$PWD/opt"
    command: ["-limit", "4","-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4445:4444"
```

browser.json:
```
{
    "internet explorer": {
        "default": "11",
        "versions": {
            "11": {
                    "image": "windows/ie:11",
                   "port": "4444",
                   "path": "/",
                   "tmpfs": {
                       /tmp": "size=128m"
                   }
            }
        }
    }
}
```
